spring:
  datasource:
    driver-class-name: org.postgresql.Driver # can remove
    url: ${DEMO_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${DEMO_POSTGRESQL_USERNAME:root}
    password: ${DEMO_POSTGRESQL_PASSWORD:root}

# Logging Levels: Fatal, Error, Warn, Info, Debug, Trace
#  보기 설정: info, debug, trace
logging:
  level:
    root: debug
